### ISSUE TITLE
Forced lowercase outputfile extension

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#1843]
`bin/ldc2 -c -output-ll test.d -of=tesT.LL`
outputs the file `testT.ll` on my system (OS X). Note the lowercase `ll`. (same for -output-s)

**Comment by rtbo** [comment]
It is not only lowercase, the extension is forced to `ll` or `s` whatever the extension provided on the command line.
I believe it has something to do with [this line](https://github.com/ldc-developers/ldc/blob/master/ddmd/dmodule.d#L396).

**Comment by kinke** [comment]
Nope that line isn't that important. The thing is that we have a single filename per object (-of or inferred) while we may output multiple files per module (.o/.bc/.ll/.s), that's why the other extensions are currently enforced. One potential fix may consist in using the filename directly if a single file is produced (but then the inferred filename needs to be adapted based on what single file is emitted, as currently the default object extension is used IIRC). It's a bit messy.

**Comment by kinke** [comment]
Fixed by https://github.com/ldc-developers/ldc/pull/1869.
