### ISSUE TITLE
LDC releases -> windows zip archives in addition to 7zip

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#2664]
I have to deal with a build system which only allows zip and tar.gz archives. Adding support for 7zip was denied to keep the amount of additional tools as low as possible.
Due to the build infrastructure rules I am also not allowed to simple download extract and archive LDC as zip archives for usage in the build infrastructure.

Could you consider to provide LDC windows releases in addition to 7zip archives also as zip archives for conservative build infrastructures?

**Comment by kinke** [comment]
Man, do I feel sorry for you for having to deal with such an archaic system. So if you cannot use a local archive, why not re-compress as zip and upload to some server? If you're allowed to download from GitHub, you probably can from other servers too (and otherwise just create a dummy GitHub project hosting your recompressed zip archive).

I'm afraid we'd soon have requests for tar.gz archives in addition to the tar.xz ones etc., doubling the files associated with each release... It'd just be a tiny change to include other formats, but I'm reluctant to do so. You're the first to complain since switching to .7z, all others seem to enjoy the ~50% size reduction IIRC.

**Comment by andre2007** [comment]
Thanks for the explanation. I close this issue.
