### ISSUE TITLE
Recent ARM buildbot failure: error reading ldc.conf

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2675]
Recently an ARM buildbot error started occurring:
```
Error: Error while reading config file: /var/lib/buildbot/slaves/scaleway/armv7_builder/build/bin/ldc2.conf
line 10: Was expecting token "string". Got ',' instead.
```
http://buildbot.ldc-developers.org/builders/armv7_builder/builds/3164

The error started happening between `Apr 21 14:45 | cd8c5a1d1385...` (good) and `Apr 23 03:44 | a9c76cff3af1...` (bad)
See builds: http://buildbot.ldc-developers.org/builders/armv7_builder

**Comment by JohanEngelen** [comment]
The armv7neon builder is doing fine: http://buildbot.ldc-developers.org/builders/armv7neon_builder/builds/329

**Comment by JohanEngelen** [comment]
@redstar Perhaps you can SSH into the box and see what's going on?

**Comment by redstar** [comment]
ldc from master builds on ARM with NEON support. There is yet no functionality like in ltsmaster (https://github.com/ldc-developers/ldc/pull/2567). It's not that straightforward to implement because of the crosscompile functionality. Therefore I patch the `CMakeList.txt` locally. One of the latest changes in master broke this patch. I updated it now. Waiting for the build now.

**Comment by redstar** [comment]
Compiles again - environment problem.
