### ISSUE TITLE
Support mangle-only extern(C++, "namespace")?

### ISSUE THREAD

**Issue by TurkeyMan** [ldc-developers/ldc#2800]
So, Walter doesn't want to support a mangling-only namespace, but comprehensive extern(C++) users are using LDC anyway because of superior ABI compatibility and perf.

Can LDC support it as an extension?

It's not unprecedented, there are already a few LDC specific extensions. Our code is not open-source, so we can make use of a compiler-specific feature safely without affecting any DMD users.
It will do a lot for my recent efforts demonstrating how D interacts with existing C++ at Bliz.

I seriously can't present the sort of code that Walter insists I write to a technical committee with a straight face.

**Comment by TurkeyMan** [comment]
I could collaborate on a DIP. Thanks for taking the initiative!
I'm fatigued by the ref one I've been working on for months to start another one right now. I carry too much frustration about this to engage reasonably with the process ;)

**Comment by kinke** [comment]
> Can LDC support it as an extension?

I'd have absolutely no problem with that, as it'd be a non-breaking change and a pure extension. Your proposal sounds good to me (and hey, may even allow for `extern(C++, "cppns.nested")` instead of ugly `extern(C++, cppns) extern(C++, nested)`).

> I'm fatigued by the ref one

Heh I feel ya. Hold out and let's right that IMO most annoying thing in the language itself. Years ago, I was willing to do my own fork in case it doesn't make it into the language.

**Comment by TurkeyMan** [comment]
I've also had this burning desire to fork for as long as these issues have existed... They're so few, and seemingly so trivial. But also so high-impact >_<

After 10 years though, I've really started to lose my cool recently. Patience only extends so far :/

**Comment by thewilsonator** [comment]
> (and hey, may even allow for extern(C++, "cppns.nested") instead of ugly extern(C++, cppns) extern(C++, nested)

That actually works currently 
```D
extern(C++, A.B.C) {}
```

**Comment by thewilsonator** [comment]
This was implemented upstream.
