### ISSUE TITLE
LDC Creating Text Relocations for Android Builds

### ISSUE THREAD

**Issue by look-at-me** [ldc-developers/ldc#2822]
This would otherwise not be a problem but Text Relocations have been disabled since Android SDK 23.
https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#text-relocations-enforced-for-api-level-23

As can be seen here, the LDC runtime build has text relocations:
https://ci.appveyor.com/project/look-at-me/android/build/1.0.53#L327

Note linker warnings are considered errors by default in the Android SDK, temporarily disabled such that a binary could be produced to investigate:
https://ci.appveyor.com/project/look-at-me/android/build/1.0.53/artifacts

```
$ scanelf -qT libmain.so
  libmain.so: _length_code [0x267A5C] in (optimized out: previous _tr_flush_block) [0x266FB1]
  libmain.so: _length_code [0x267B10] in (optimized out: previous _tr_tally) [0x267A75]
  libmain.so: _dist_code [0x267A68] in (optimized out: previous _tr_flush_block) [0x266FB1]
  libmain.so: _dist_code [0x267B14] in (optimized out: previous _tr_tally) [0x267A75]
  libmain.so: z_errmsg [0x26805C] in (optimized out: previous zError) [0x26804D]
  libmain.so
```

As can be seen the text relocations are related to zLib in phobos. Now with the patch from https://github.com/ldc-developers/phobos/pull/47 being installed and run, as can be seen there is no warning message as the text relocations have been removed:
https://ci.appveyor.com/project/look-at-me/android/build/1.0.54#L342

If the `scanelf` command is run on the shared object file we can confirm that the text relocations have been erased:
https://ci.appveyor.com/project/look-at-me/android/build/1.0.54/artifacts

The bug appears to be in LLVM as the source files are compiled with PIE. Removing the arrays of data from the source file they were used, into their own source file effective did what PIE is supposed to do when it is working correctly. A text relocation can't be created if the compiler doesn't know where the data is, since it has been moved to a different source. Each source file is compiled individually, so it is impossible for it to know where the data is located at compile time, removing the text relocations even though it looks like the change does nothing :) !

**Comment by joakim-noah** [comment]
Thanks for reporting, I'll look into it.

**Comment by kinke** [comment]
According to [SO](https://stackoverflow.com/questions/33659673/android-ndk-are-fpic-and-pie-mututally-exclusive), this is probably only a matter of replacing the currently used `-fpie` by `-fPIC` in the Android C [compile+link flags](https://github.com/ldc-developers/ldc/blob/master/runtime/PresetRuntimeConfiguration.cmake#L26-L37).

**Comment by joakim-noah** [comment]
OK, I can finally reproduce this problem with the first apk example from the wiki, if I add a `writeln` to it. Someone reported this issue before, but I couldn't reproduce with the unmodified wiki examples or with the test runner shared library, which has the linker check for text relocations. If I link a release version of Phobos built with the tests, ie `libphobos2-ldc-unittest.a`, into the modified `native-activity` example, there aren't any text relocations anymore, which is weird because the C files for both versions of Phobos _should_ be built the same way. I'll investigate further and let you know.

>probably only a matter of replacing the currently used -fpie by -fPIC

Those flags you link are only used to build the `{druntime,phobos2}-test-runner*` executables, I don't use them to build any shared libraries. When I build the test runner shared library, I supply different linker flags, [as can be seen here](https://gist.github.com/joakim-noah/d74af3cf1355492557a9c56ef1bf2636#file-ldc_1-3_android_arm-L32).

**Comment by kinke** [comment]
I.e., `-fpic` for the C parts and `-fPIE -pie` for linking AFAICT. I'd definitely try `-fPIC` for both.

**Comment by joakim-noah** [comment]
@kinke got close, [there's an `-fpie` when compiling the C files in Phobos now](https://github.com/ldc-developers/ldc/blob/master/runtime/PresetRuntimeConfiguration.cmake#L26), which wasn't there [when I used to build the stdlib for ldc 1.3 and before](https://gist.github.com/joakim-noah/d74af3cf1355492557a9c56ef1bf2636#file-ldc_1-3_android_arm-L30). Looking at the clang flags used when building a C executable or shared library with the `ndk-build` script from the NDK, it doesn't add the `-fpie` flag when compiling a C file for a shared library. I think I figured I'd just keep it since it probably won't make a difference- though I don't remember- but apparently this `-fpie` flag broke Android shared libraries sometimes since ldc 1.4.

@look-at-me, you can verify by starting `ldc-build-runtime`, modifying the preset target configuration to not add that flag, and then running the same `ldc-build-runtime` command with the `--reset` flag added. That's what I just did and it fixed the text relocation problem for me. I'll submit a pull to remove that flag.

**Comment by look-at-me** [comment]
Yah looks like that fixed it, thanks.
