### ISSUE TITLE
Release schedule?

### ISSUE THREAD

**Issue by FeepingCreature** [ldc-developers/ldc#2857]
`ldc 1.12` has been in beta for twenty days. Is it ever going to be not beta? Or is `-beta1` sort of the inofficial release "by default"?

**Comment by kinke** [comment]
1. We require at least one DMD patch release (2.082.1) to guarantee some stability/less regressions for our final.
2. 1.12 final may be based on LLVM 7, although there's a serious long-double-to-ulong conversion regression on Linux x86[_64]. If we choose LLVM 7, there'll be another beta.
3. I'm waiting for https://github.com/dlang/druntime/pull/2307 and https://github.com/dlang/dmd/pull/8729 to land upstream into `stable`, otherwise DMD master cannot be built with LDC 1.11+ on Win32. https://github.com/ldc-developers/ldc/pull/2852 is another prerequisite for building DMD successfully on both Win32 and Win64.
4. Please use the forum or gitter for questions.
