### ISSUE TITLE
Subsequent assignment to same varible from ctRegex causes runtime segfault

### ISSUE THREAD

**Issue by aldem** [ldc-developers/ldc#2961]
Hi,

While trying ldc2-1.13.0-linux-x86_64 on Ubuntu 18.04, I have encountered strange app segfault.

The following code:
 ```D
   auto re = ctRegex!(r"^$");
   re = ctRegex!(`ab`);
 ```
compiles without any issues but produces segfault on second call to ctRegex. If I assign regex to re only once, or when I use different variables, it works without any issues. However, in all cases it works perfectly with dmd 2.083.1

Actually, regex itself has little to do with this problem - almost anything will segfault, as long as there is more than one call to ctRegex which is assigned to same variable.

gdb backtrace is quite unhelpful:
```
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:340
#1  0x0000555555571615 in main (args=...) at re-fail.d:10
```
and points to the line with second assignment.

Since it works with dmd, I guess this is somehow related to code generation in ldc. Playing with -O flag didn't change anything, -mcpu also seems to have no effect.

**Comment by kinke** [comment]
Oh, this smells like lovely dirty Phobos hackery.

`re = ctRegex!(`ab`)` isn't a simple assignment of the (empty - still 1-bytes large) `ctRegexImpl!(...).Wrapper` struct - due to `alias this` witchcraft, it's `re.getRe() = Wrapper().getRe()`. The return value of `getRe()` is a `Regex!Char` (168 bytes on Win64). Now the fun part in `std.regex.package`:
```D
static immutable staticRe =
    cast(immutable) r.withFactory(new CtfeFactory!(BacktrackingMatcher, Char, func));
struct Wrapper
{
    // allow code that expects mutable Regex to still work
    // we stay "logically const"
    @property @trusted ref getRe() const { return *cast(Regex!Char*)&staticRe; }
    alias getRe this;
}
```

This `logically const` doesn't work for us, as `static immutable staticRe` is most likely emitted as read-only, and copying the `ab` constant to the `^$` one will fail (and should be as wrong as it gets - it's probably fun when later trying to work with the same `ctRegex!(r"^$")`, as it probably behaves as `ctRegex!("ab")` after that assignment...).

**Comment by kinke** [comment]
Yep, it's as bad as expected; with DMD:
```D
import std.regex;

void main()
{
    auto re = ctRegex!("hello");
    auto r1 = matchFirst("hello world", re);
    assert(r1);
    re = ctRegex!("bar");
    auto r2 = matchFirst("hello world", ctRegex!("hello"));
    assert(r2);
}
```

The 2nd assert fails. - Reassigning a `Wrapper` struct returned by `ctRegex` should probably be forbidden. Please file a DMD bug report, thanks!

**Comment by kinke** [comment]
Proposed upstream fix: https://github.com/dlang/phobos/pull/6852
