### ISSUE TITLE
`-disable-fp-elim` option is changed in LLVM

### ISSUE THREAD

**Issue by JohanEngelen** [ldc-developers/ldc#2980]
This will require some small changes: https://reviews.llvm.org/rL351049

**Comment by jondegenhardt** [comment]
Does the change in PR #2983 have the effect of changing the command line arguments passed to `ldc`?

**Comment by kinke** [comment]
With LLVM 9, yes. Are you using that flag and do you need a legacy option?

**Comment by jondegenhardt** [comment]
Yes, I use that flag, but selectively. I'm sure you'll remember some of the long reports I filed on difficult to track down issues involving LTO. These typically involved `std.getopt` with large argument lists.

For a couple of my command lines tools the only identified way to address the problem was to use this flag. So, I turn it on for the command line tools encountering trouble.

My build setup is designed to support multiple versions of dmd and ldc. Its a bit of a pain if the build needs condition the compiler command line arguments based on compiler version. Doable, but an issue.

So for me, it'd be nice if there was a compiler option independent of version.

**Comment by kinke** [comment]
Legacy option implemented, as the LLVM change got cherry-picked for LLVM 8.
