### ISSUE TITLE
FreeBSD: switch to using external (libexecinfo) backtrace function like GDC does

### ISSUE THREAD

**Issue by myfreeweb** [ldc-developers/ldc#3108]
The custom backtrace impl at https://github.com/ldc-developers/druntime/blob/ldc/src/core/sys/freebsd/execinfo.d is not working properly on my amd64 machine currently (only shows `_d_createTrace`), even though it might have worked on aarch64 when I added the `llvmasm` thing for it..

GDC is actually using libexecinfo instead of this mess (`version (GNU) version = BacktraceExternal;`). I think LDC should do the same. It actually works :) and it's portable to all architectures.

The plan is:

- druntime: `version (LDC) version = BacktraceExternal;`
- druntime: `version (LDC) { numframes = cast(int)backtrace( callstack.ptr, MAXFRAMES ); }` (execinfo's backtrace returns a `size_t`, add an int cast) (hmm this is only in ldc's fork!)
- LDC/runtime/cmake: add execinfo to `C_SYSTEM_LIBS` for shared druntime
- LDC/driver/linker-gcc: add execinfo to `addDefaultPlatformLibs` for static druntime (is this the right place???)

Do you agree?

---

https://github.com/myfreeweb/ldc/commit/573cb1456b1074bb4ab604a838658f30beb6a797
https://github.com/myfreeweb/druntime/commit/4cc671669d45f14cc8fd270857d5cbeae6b38be8

**Comment by kinke** [comment]
I think this should be discussed upstream, the only LDC-specific aspect here is the question about how to implement the proposed additional C lib dependency - I'd propose a `pragma(lib, "execinfo");` for FreeBSD there instead of tampering with CMake and new hardcoded lib. The ~150 D lines don't look that bad though IMO; trying to figure out & fix the issue(s) might be worthwhile.

**Comment by myfreeweb** [comment]
yeah, `pragma` is a good idea!

> due to non-x86 archs

Indeed — the worst part of those D lines, other than that they're reinventing part of the system's public API, is that it touches inline assembly.

> should be discussed upstream

Well, upstream would probably like to know that LDC has agreed to work with the `version (LDC) version = BacktraceExternal` change :)

**Comment by kinke** [comment]
> yeah, pragma is a good idea!

It might not work for non-Windows though; I think the module with the pragma needs to be imported somewhere in the cmdline performing the linking. For MSVC, we can embed linker cmdline args in the object file, so there the pragma should be sufficient.

> Well, upstream would probably like to know that LDC has agreed to work with the version (LDC) version = BacktraceExternal change :)

I assume this FreeBSD implementation doesn't work upstream either, that's why I think the discussion whether to fix or simply get rid of it should be held upstream.

**Comment by kinke** [comment]
Switched in https://github.com/ldc-developers/druntime/commit/936154ac4613ff9ff169820c0d9d8a057d9c26e7; `pragma(lib, "execinfo");` now works properly for ELF targets when using lld 9+ (supporting the special `.deplibs` object file section).
