### ISSUE TITLE
Memory corruption with LDC2 and -O3

### ISSUE THREAD

**Issue by jblachly** [ldc-developers/ldc#3137]
*Crosspost from the newsgroup (low traffic); not sure best place for this*

Hi all,

First , as always thanks for LDC2 without which we couldn't write high performance D software for our lab.

I've run in to an problem wherein after ~60,000 iterations of a loop we get memory corruption, but only when building with LDC2 and -O3; there are no problems AFAICT with -O2, or when building optimized versions with DMD. -enable-inlining does not make a difference. All of that being said, it does not rule out me making a pointer or memory error, but all seems well except with LDC2 -O3.

I've build a debug version with ASAN which reports some leaks, but no out-of-bounds accesses or other memory problems.

Debugging has been difficult because -O3 optimizes away a lot and thus lldb is not able to show me the tracking debugging variables I need to isolate the problematic code. Disassembling, I've found the register storing pointer to the corrupt string; interestingly, the correct string appears just slightly lower on the heap (maybe 32 bytes IIRC).

Manifestation slightly nondeterministic -- adding tracking variables and code makes the problem intermittent.

Indeed, I placed some simple guards (e.g.: `if (pre_string != post_string) throw new Exception()` ) near the place where the corrupt memory is manifest and **sometimes the guard is triggered, while other times it is _not_, but the bad string shows up just a few statements later (inside a function).**

Am at my wits' end, so help or next steps are greatly appreciated. I can provide disassembly of whatever combination of -O/-O2/-O3 and triggering/nontriggering code blocks if it would be helpful.

Kind regards

**Comment by kinke** [comment]
I don't think we can solve this here, especially without *any* code, used LDC+LLVM version and targeted platform, used compiler flags etc. etc.

It it works reliably with -O2, I'd say it's much more likely to be either a bug on your side or an LLVM bug than an LDC bug. DMD isn't a reference for aggressive optimization, so a comparison with gdc could be helpful.
Just out of curiosity, are you using inline asm?

> -enable-inlining does not make a difference

It's implied by `-O`. DMD is one of the probably extremely few compilers on earth not defaulting to inlining with enabled optimizations, probably because its implementation is rather exotic (read: awfully slow).

**Comment by jblachly** [comment]
Of course you are probably right. I was really preliminarily asking if this is an appropriate venue before pasting a bunch of code from a closed repository.

We are not using inline asm, but we are calling an external C library (for which I have source and AFIACT does not clobber any of our dlang memory).

I will close the issue and search harder, or open a bug bounty once we open the code repo.

Kind regards
