### ISSUE TITLE
Linux/AArch64: Fall back to clang when gcc is unavailable for linking

### ISSUE THREAD

**Issue by kettes-leulhetsz** [ldc-developers/ldc#3175]
I'm investigating a barrage of link errors on Termux/Android. Notably, dub fails to test anything with `unit-threaded`.

(My actual goal is parallel ThinLTO with bitcode from C/C++ too. No combination of linker flags seems like it would work with more linker flags.)

Termux doesn't have gcc. Long story short: Termux uses the Android system dynamic linker, which hardcodes `/system/lib64/libc++.so` even in C programs, so it actually makes sense to remove gcc in favor of clang.

LDC (by default) refuses to link anything without gcc, so the Termux packaging team solved it... symlinking gcc -> clang. I consider it a small miracle anything is working at all with this setup.

This is not Termux-specific, LDC seems to use gcc on Arch Linux ARM too.

So far I've failed to find the necessary options to make LDC link with clang as the driver, though I admit I haven't tried looking very hard.

**Comment by kinke** [comment]
You can either set the CC env variable, or specify the linker driver via `-gcc=clang`. Can be put inside `etc/ldc2.conf`. Looks like a reasonable addition to https://github.com/termux/termux-packages/pull/4286.

**Comment by kinke** [comment]
As for actual linker, I got undefined reference errors with `gold` for armv7a wrt. `__bss_end__`, so that `-linker=bfd` was needed. That's Android-specific though (not Linux).

#3164 adds an official prebuilt Android armv7a package. It's only cross-compiled and -linked for now, no tests whatsoever are run on Android. `libc++` is linked statically. Of course it still needs a C compiler and libs for linking. Tests/contributions are highly welcome; the .tar.xz archive can be downloaded as Azure artifact (https://dev.azure.com/ldc-developers/ldc/_build/results?buildId=731, click on the top-right burger button -> Artifacts -> ...).

**Comment by kinke** [comment]
I think the proper fix would be to invoke `cc` by default (if the `CC` env variable isn't set), not `gcc`. That's what DMD does too.

**Comment by kinke** [comment]
Defaulting to `cc` now with #3202, so IMO this is resolved.
