### ISSUE TITLE
building from source failed

### ISSUE THREAD

**Issue by adamdruppe** [ldc-developers/ldc#3188]
I downloaded, git submodule init, cmake ., make and it spat this out:

[ 27%] Built target LDCShared
make[2]: *** No rule to make target 'lib/libldmd.a', needed by 'bin/ldmd2'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:126: CMakeFiles/ldmd2.dir/all] Error 2

did i miss something or is the makefile broken?

**Comment by kinke** [comment]
We don't recommend building with make, but ninja instead (https://wiki.dlang.org/Building_LDC_from_source), though such an error should obviously never surface (and I've never seen it).

**Comment by kinke** [comment]
> well a fresh thing with ninja worked this time

Using the src dir directly as build dir again, as the 1st try with make? I've never tried that.

> i'm willing to close this as user error if you all have never seen it either

It's strange because AFAIK we don't have any special logic for ninja/make at all. I assume you're using GNU make?

> btw I kinda wanna work on porting the objective C stuff from dmd over to ldc

All the best. You don't need to start from 0, it's only the 2.080 and 2.085 additions (#3007, #2670) that haven't been ported. [I haven't heard a single request/complaint so far.]

**Comment by Alzimzim** [comment]
> I downloaded, git submodule init, cmake ., make and it spat this out:
> 
> [ 27%] Built target LDCShared
> make[2]: *** No rule to make target 'lib/libldmd.a', needed by 'bin/ldmd2'. Stop.
> make[1]: *** [CMakeFiles/Makefile2:126: CMakeFiles/ldmd2.dir/all] Error 2
> 
> did i miss something or is the makefile broken?

I rolled back to v1.17.0 
1.18.0-beta2 does not work build with LLVM9

**Comment by kinke** [comment]
> maybe something crept into the cmake thingy

Indeed, very recently in the Android [PR](https://github.com/ldc-developers/ldc/pull/3164).
