### ISSUE TITLE
Make gccbuiltins_*.di available to uninstalled LDC in build folder 

### ISSUE THREAD

**Issue by bioinfornatics** [ldc-developers/ldc#3194]
Dear,

I tried to build [asdf](https://github.com/libmir/asdf/) with the dflags `-mattr=+sse4.2` and got this error
```
ERROR   d-llvm-1.18.0: ../source/asdf/jsonparser.d(36): Error: module gccbuiltins_x86 is in file 'ldc/gccbuiltins_x86.d' which cannot be read
```

A github search show that some packages use this module but I do not found the corresponding file

I see some ldc's discussion which mention the module as this [one](https://github.com/ldc-developers/ldc/issues/595#issuecomment-39845318)

is it generated automatically if we provides some magic flag when building ldc ?

Thanks for your help

**Comment by dnadlinger** [comment]
It is automatically generated when building the usual way via CMake, no magic flag needed.

**Comment by JohanEngelen** [comment]
When building LDC the file can be found in the `runtime` subdirectory of your build folder. So the file is not yet in its final position and cannot be found by the LDC binary in the build folder. You have to install LDC to some folder and then the file is put in the correct location.

Indeed I see this as a bug, because it means we cannot use gccbuiltins for any integration test. Solution:
- put gccbuiltins files into `<buildfolder>/runtime/ldc` (instead of `<buildfolder>/runtime`)
- add `-I<buildfolder/runtime` to `post-switches` in the ldc.conf in the build folder.

**Comment by bioinfornatics** [comment]
thanks
