### ISSUE TITLE
Linker errors when building DMD dub package on Windows

### ISSUE THREAD

**Issue by GoaLitiuM** [ldc-developers/ldc#3212]
With LDC2 1.17 and 1.18, building DMD as a library with dub fails with following linker errors:
```
WARNING: A deprecated branch based version specification is used for the dependency dmd. Please use numbered versions instead. Also note that you can still use the dub.selections.json file to override a certain dependency to use a branch instead.
Running pre-generate commands for dmd:lexer...
Performing "$DFLAGS" build using ldc2 for x86_64.
config ~master: target for configuration "application" is up to date.
To force a rebuild of up-to-date targets, run again with --force.
Running ..\..\..\..\..\GoaLitiuM\AppData\Local\dub\packages\dmd-master\dmd\generated\dub\config.exe C:\Users\GoaLitiuM\AppData\Local\dub\packages\dmd-master\dmd\generated/dub C:\Users\GoaLitiuM\AppData\Local\dub\packages\dmd-master\dmd\VERSION
Performing "debug" build using ldc2 for x86_64.
dmd:root ~master: building configuration "library"...
dmd:lexer ~master: building configuration "library"...
dmd:parser ~master: building configuration "library"...
dmd:frontend ~master: building configuration "library"...
dmdtestldc2 ~master: building configuration "application"...
lld-link: error: undefined symbol: _D3dmd7backend2el4elem6__initZ
>>> referenced by dmd_frontend.lib(dmd.root.array.obj):(_D30TypeInfo_S3dmd7backend2el4elem6__initZ)

lld-link: error: undefined symbol: _D3dmd7backend2cc6Symbol6__initZ
>>> referenced by dmd_frontend.lib(dmd.root.array.obj):(_D32TypeInfo_S3dmd7backend2cc6Symbol6__initZ)

lld-link: error: undefined symbol: _vsnprintf
>>> referenced by C:\Users\GoaLitiuM\AppData\Local\dub\packages\dmd-master\dmd\src\dmd\root\outbuffer.d:304
>>>               dmd_frontend.lib(dmd.root.outbuffer.obj):(public: void __cdecl OutBuffer::vprintf(char const *, char *))
Error: linking with LLD failed
ldc2 failed with exit code 1.
```
Same errors with MSVC linker but without the undefined `_vsnprintf` symbol. No issues when building on 64-bit Arch Linux, and no issues with `--compiler=dmd` on either system.

How to reproduce:
```
dub init -n
dub add dmd
dub build --compiler=ldc2 --force
```

**Comment by kinke** [comment]
Wrt. `_vsnprintf`, that's just a missing alias in the MinGW-based libs; can be fixed by switching to standard `vsnprintf`.

Wrt. the 2 missing init symbols (expected for non-templated backend structs) referenced from 2 TypeInfos (both emitted into `dmd.root.array.obj`), I bet that only works with LDC on Linux due to linker stripping, i.e., the 2 TypeInfos not really being referenced anywhere; the MS linker (and lld-link.exe) strips symbols *after* resolving AFAIK and is thus more susceptible to linker errors.

As you state that it works with DMD on Windows (I assume with `-m64` for comparableness), this possibly means that LDC is uselessly emitting unused TypeInfos which DMD isn't.

**Comment by GoaLitiuM** [comment]
This PR seems to have introduced the issue if it's any help: https://github.com/dlang/dmd/pull/10478

**Comment by GoaLitiuM** [comment]
I accidentally replicated the same set of linker errors with DMD while fiddling with the build process, and I can replicate this on Linux as well (Linux LDC seems to be safe from this).

Basically, I changed the build process so each of the subpackage spits out object files, and then links those object files to the final static library in a separate step, and that seems to cause these linker errors across the board. It does seem like LDC does something similar in this case when building the project with dub.

Here's all the build commands and the test app which can reproduce this when ran against current master branch of DMD: https://gist.github.com/GoaLitiuM/4958c173a9af91864272a931881b1c95
Simply changing dmd -> ldmd2 can reproduce the errors with LDC on Windows, but on Linux, ldmd2 passes with no errors.

I'll report this to DMD bug tracker as well, but feel free to close this if it doesn't look like it applies to LDC directly.

**Comment by kinke** [comment]
Wrt. DMD on Linux: it uses `--export-dynamic` for `ld` by default AFAIK, and that prevents linker stripping. I guess you see the same issues with LDC on Linux when using `-L--export-dynamic` or `-disable-linker-strip-dead`.

> It does seem like LDC does something similar in this case when building the project with dub.

Well something like that, i.e., LDC compiling to multiple objects and DMD to a single one, is definitely not expected and should be investigated; might be a dub issue. Running dub with `-v` shows the issued compiler cmdlines.

If it works when compiling each package to a single object, the question is where the 2 problematic TypeInfos end up, and whether it only works accidentally in this case, e.g., because that object file isn't referenced in your tiny sample app, or if it isn't emitted at all because the compiler thinks it doesn't have to (figuring that it's going to be in the backend package object file anyway and so eliding its emission, and getting lucky because the backend sources aren't compiled & linked because not needed).

**Comment by kinke** [comment]
*Actually* I think DMD-as-a-library shouldn't depend on any backend symbols. There are clearly some usages of `dmd.backend.el.elem`; there's an alias somewhere (e.g., LDC clearly uses another type for its backend) which should probably be changed to some placeholder or opaque pointer when compiling DMD as a lib.

**Comment by kinke** [comment]
After a quick glance, there appear to be 2 dub-included modules importing backend modules: `dmd.irstate` and Windows-specific `dmd.tocvdebug`. The first should probably use the symbols from `dmd.gluelayer` (which uses opaque structs for `version (NoBackend)`), and the 2nd can probably be excluded from the `frontend` dub subpackage.

**Comment by GoaLitiuM** [comment]
That PR seems to indeed fix the issue 👌
