### ISSUE TITLE
Alpine LDC package: cannot find -lphobos2-ldc

### ISSUE THREAD

**Issue by andre2007** [ldc-developers/ldc#3254]
I am not sure whether this is the correct place to report the issue?
This dockerfile

```dockerfile
FROM alpine:edge as build
RUN apk add build-base ldc dub --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted

WORKDIR /tmp
COPY app.d /tmp
RUN dub build --single app.d
```

fails with:
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld.bfd: cannot find -lphobos2-ldc
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld.bfd: cannot find -ldruntime-ldc
collect2: error: ld returned 1 exit status
Error: /usr/bin/gcc failed with status: 1
/usr/bin/ldc2 failed with exit code 1.
The command '/bin/sh -c dub build --single app.d' returned a non-zero code: 2

**Comment by kinke** [comment]
It's not the correct place, we don't officially support any distro packages.

**Comment by Geod24** [comment]
For reference, you currently need to install `ldc` and `ldc-static` for things to work.
It's a limitation in the current packaging that I am going to fix at some point.

**Comment by kinke** [comment]
@Geod24: In case the issue is that the `ldc` package contains shared libs only, you could add `-link-defaultlib-shared` to `default.switches` in the config file, defaulting to the shared libs with `-shared` suffix. The user could then override explicitly with `-link-defaultlib-shared=false` to select the static libs after installing `ldc-static`.

**Comment by Geod24** [comment]
Well there is also shared libraries, but it's another package (`ldc-runtime`).
The issue at hand is really that I forgot to add the dependency, and due to the way I packaged it, I can't fix it at the moment.
I'm going to rewrite the package based on GDC, so that bootstrapping works correctly, and will solve the issue at the same time.
