### ISSUE TITLE
Extend ldc-build-runtime for wasm

### ISSUE THREAD

**Issue by skoppe** [ldc-developers/ldc#3315]
So I finally figured out all the changes required to have `ldc-build-runtime` build a webassembly version of druntime and phobos.

I have added a wasm32 preset and some config to `PresetRuntimeConfiguration.cmake`. This works wonders but still leaves 2 small issues:

1) we need to download a sysroot from https://github.com/CraneStation/wasi-sdk/releases that contains a prebuild `libc.a` that sits atop of the WASI interface, as well as C headers for compiling some C files in phobos. The question is where to store this.
2) we need to depend on clang for said C files as gcc doesn't target wasm, right now I am using `CC=clang-9 ldc-build-runtime --targetPreset wasm32 --ninja --ldcSrcDir ../`, but I don't know it that suffices.

**Comment by kinke** [comment]
A PR would probably be better suited for a discussion, to make things concrete. - I was going to deprecate these target presets, as the only existing ones for Android can be handled in a much simpler and future-proof way via a provided CMake toolchain file. I've checked the linked WASI SDK, and it comes with a cmake file too (`share/cmake/wasi-sdk.cmake`), so that I think this should be rather trivial too.

As to whether the ldc-build-runtime tool is the suited tool for downloading such an SDK is questionable; we don't download any other prebuilt toolchain for other targets, plus as soon as those WASI libs are shipped with prebuilt LDC, there's hardly much reason to build them yourself anymore.

**Comment by kinke** [comment]
What I mean is that once I download and extract the prebuilt WASI SDK into `/home/me/wasi-sdk`, a cmdline like this (similar to the Android one) should do:
```
ldc-build-runtime --ninja --dFlags="-mtriple=wasm32-unknown-wasi" -DCMAKE_TOOLCHAIN_FILE="/home/me/wasi-sdk/share/cmake/wasi-sdk.cmake" -DWASI_SDK_PREFIX="/home/me/wasi-sdk"
```

In `runtime/CMakeLists.txt`, variable `TARGET_SYSTEM` will probably be set to `Wasm`, according to the wasi-sdk.cmake file, and can be used to special-case the druntime/Phobos build for WASI.

Prebuilt `libc.a` from the WASI SDK is analogous to the libc dependency of the C cross-toolchain for other targets. Unlike Posix targets, WASI targets are suited for direct linking with LLD though (no need to link through C cross-compiler), so it makes sense to ship with that prebuilt lib (hoping that's really all, and that there are no special startup and shutdown object files...), so that the user doesn't need the WASI SDK for linking (analogous to Windows, where we ship with MinGW-based libs to be independent from the MS toolchain).

**Comment by skoppe** [comment]
Ok, I understand, thx for the info.

There isn't much inside `crt1.o` see https://github.com/CraneStation/wasi-libc/blob/master/basics/crt/crt1.c, we can call that ourselves as well (for the most part I already do https://github.com/skoppe/druntime/blob/wasm/src/core/internal/entrypoint.d#L55).
