### ISSUE TITLE
_rt_loadLibrary symbol not found 

### ISSUE THREAD

**Issue by jda-iocom** [ldc-developers/ldc#3331]
I'm trying to compile a small test program:

```
module MacOS.tf;

import std.stdio;
import core.runtime;

void main() {
  void* vhandle = Runtime.loadLibrary("igvideo");
}
```
on Mac OSX Catalina, and I am getting the following error:

```
(ldc-1.20.0) ldc2 tf.d
Undefined symbols for architecture x86_64:
  "_rt_loadLibrary", referenced from:
      __D4core7runtime7Runtime__T11loadLibraryZQoFMxAaZPv in tf.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: /usr/bin/cc failed with status: 1
```

**Comment by dnadlinger** [comment]
Are you linking against the shared version of druntime?

**Comment by jda-iocom** [comment]
No idea! That's all I'm typing in - ldc2 tf.d

**Comment by kinke** [comment]
Then try with `-link-defaultlib-shared`.

**Comment by jda-iocom** [comment]
Nice! That fixed it. Should I leave this bug opened though?

**Comment by kinke** [comment]
There's an [upstream issue](https://issues.dlang.org/show_bug.cgi?id=16391) wrt. this. It doesn't apply to LDC, as we use the same proper shared-libs mechanism for Mac as on Linux.

According to the comment for `Runtime.loadLibrary()`, I wouldn't assume that the function is only available in the shared libs though, and especially wouldn't expect an ugly linker error. So that might be worth another issue, upstream though as not really LDC-specific.
