### ISSUE TITLE
need help to debug stack_not_16_byte_aligned_error on macOS 10.15

### ISSUE THREAD

**Issue by changloong** [ldc-developers/ldc#3384]
I get this error when build with `lto` for macOS 10.15 with latest ldc:

```sh
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00007fff6cc882be libdyld.dylib`stack_not_16_byte_aligned_error
libdyld.dylib`stack_not_16_byte_aligned_error:
->  0x7fff6cc882be <+0>: movdqa %xmm0, (%rsp)
    0x7fff6cc882c3 <+5>: int3   
    0x7fff6cc882c4 <+6>: nop    
    0x7fff6cc882c5 <+7>: nop    
```

There is no backtrace and symbols name even I build it with `-g -O0`, and without lto there is no error.

Is there a way to find what cause this ?

**Comment by kinke** [comment]
According to Google search results, this seems to be an Xcode 11 issue (enabling stack alignment checks), and might be fixed in the latest Xcode 11 version. LDC is almost certainly not to blame (as for most, if not all other LTO-related issues).

https://forums.developer.apple.com/thread/121887
https://github.com/jedisct1/libsodium/issues/848
https://trac.ffmpeg.org/ticket/8073

**Comment by changloong** [comment]
hi @kinke 
Thanks for the quick reply,  add ` -fno-stack-check` fix the problem.
