### ISSUE TITLE
Valid assembly rejected in 32-bit x86 + Linux

### ISSUE THREAD

**Issue by p0nce** [ldc-developers/ldc#3565]
**Consider the following program:**

```d

/////////////// test.d ////////////////
align(16) static immutable int[4] xmmTwoInt = [ 2, 2, 2, 2 ];
align(16) static immutable float[4] xmm0_5 = [ 0.5f, 0.5f, 0.5f, 0.5f ];

void test()
{
    for (int y = 0; y < 222; ++y)
    {
        void* L0;
        void* L1;
        void* dest;
        asm
        {
            mov ECX, 2222;
            mov EAX, L0;
            mov EDX, L1;
            mov EDI, dest;
            pmovmskb ESI, XMM2;
            pshufd XMM0, XMM0, 0b00001000;
            pshufd XMM3, XMM3, 0b00001000;
            addps XMM0, xmm0_5;
            paddd XMM1, xmmTwoInt;
        }
    }
}
```

**Command-line:**
` $ ldc2 test.d -march x86` 

**Compiler:**
LDC 1.23, LDC 1.18 for Linux x86_64 and probably others
No problem for 64-bit, or with DMD.

**Output:**
` error: inline assembly requires more registers than available`

**Expected:**
Either something more informative or some clever register usage.

**Comment by kinke** [comment]
Interestingly, this works for `-mtriple=i686-windows-msvc`, but not for `i686-linux-gnu`, although the IR is identical. It's the LLVM assembler complaining, so there's not much room to be more informative.  - This is due to the poor DMD-style-asm-to-LLVM-asm conversion (look at the IR if you dare) and not likely to be improved anytime soon; I'm only focused on GDC-style asm.

**Comment by p0nce** [comment]
Yes, it was just for documenting. This assembly block is to be rewritten in intel-intrinsics anyway as it's more portable and usually quicker. You can close this ^^
