### ISSUE TITLE
build failure in dmd ci with new release

### ISSUE THREAD

**Issue by thewilsonator** [ldc-developers/ldc#3596]
https://buildkite.com/dlang/dmd/builds/16899#3af972d5-749b-48cd-958f-7f3f4b1e6242

https://github.com/dlang/dmd/pull/11904

Seems to be recent and unrelated to the PR in question. Any ideas on the LDC side? Will look into it tomorrow more carefully.

**Comment by kinke** [comment]
Fortunately not that big a deal - probing the D host compiler for manual linking doesn't take into consideration the CMake build type since #3575; that means that it tries to link the test program against release druntime/Phobos, which are excluded from the first build (only builds the debug libs in https://github.com/dlang/ci/blob/81e51f4d135e6539eeb2520f3c204a360f49eb5f/buildkite/build_project.sh#L253). I'll prepare a Buildkite workaround via `-DLDC_LINK_MANUALLY=OFF`.

**Comment by thewilsonator** [comment]
Thanks

**Comment by kinke** [comment]
https://github.com/dlang/ci/pull/435
