### ISSUE TITLE
Enums are not showing up correctly as members of a struct when debugging.

### ISSUE THREAD

**Issue by 12345swordy** [ldc-developers/ldc#3688]
```
enum B : byte {x,y}

struct Y {B A;}
int main()
{
Y y = { A:B.x };
return 0;
}

```
Set breakpoint at ```return 0;``` and you will see A as A = 0

**Comment by Geod24** [comment]
Which version of LDC ? Of LLDB ? Or is it GDB ? And which platform ?

**Comment by 12345swordy** [comment]
1.24.0 windows, visual studio debugger.

**Comment by quickfur** [comment]
Also happens with LDC 1.25.1 on Linux 64-bit:
```
import std;
enum E { abc, def, ghi }
struct S {
	E e;
}
void fun(S s, E e) {
	writeln(s.e);
}
void main() {
	fun(S(E.def), E.ghi);
}
```

Compile with `ldc2 -g prog.d`.

In gdb:

```
(gdb) break prog.fun
Breakpoint 1 at 0x29538: file prog.d, line 6.
(gdb) run
Starting program: /tmp/prog 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, prog.fun(prog.S, prog.E) (s=..., e=prog.abc) at prog.d:6
6	void fun(S s, E e) {
(gdb) p e
$1 = prog.abc
(gdb) p s.e
$2 = 0
```

Expected output:
1. `e` should be displayed as `prog.E.def`, not `prog.abc`.
2. `s.e` should be displayed as `prog.E.ghi`, not 0.

Curiously enough, if the line in `main` is changed to:

```d
	fun(S(E.ghi), E.def);
```

then the output from gdb becomes:

```
(gdb) break prog.fun
Breakpoint 1 at 0x29538: file prog.d, line 6.
(gdb) run
Starting program: /tmp/prog 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, prog.fun(prog.S, prog.E) (s=..., e=prog.abc) at prog.d:6
6	void fun(S s, E e) {
(gdb) p s 
$1 = {e = 0}
(gdb) p e
$2 = prog.abc
```

Notice the switched order where `0` is printed, and `abc` being displayed where the value is `def`. The enum identifiers seem to have been shifted or shuffled, with `0` replacing one of the values. Possibly an off-by-1 error somewhere?

**Comment by kinke** [comment]
Thx for the report.

@quickfur: Please consider creating a separate issue about the arguments order. I suspect a problem due to the reversed args order for `extern(D)`; we encode it in DWARF via a proposed calling convention addition IIRC, but have no idea which debuggers support it (if at all). And before wasting more time for that, I'd be inclined to finally get rid of the arguments reversal, breaking naked DMD-style asm functions using registers to access params in the process, but finally adhering to the D ABI spec.
