### ISSUE TITLE
Trojan detection for libcurl.dll (ldc v1.24.0)

### ISSUE THREAD

**Issue by SingingBush** [ldc-developers/ldc#3717]
There have been [issues about this before](https://github.com/ldc-developers/ldc/issues?q=is%3Aissue+trojan) (#3448, #3472, #3642) but am raising again as it doesn't seem to have been resolved fully.

Detected *Trojan:Win32/Ymacco.AA5B* in `C:\tools\ldc2-1.24.0-windows-x64\bin\libcurl.dll`

![image](https://user-images.githubusercontent.com/870567/117570372-b9f5c300-b0c1-11eb-8b4c-80f133de890c.png)

I'm using the ldc that's published via chocolatey: https://community.chocolatey.org/packages/ldc

**Comment by SingingBush** [comment]
I guess part of this problem is that the last few releases have not been published to chocolatey

**Comment by kinke** [comment]
The Chocolatey package is not maintained by us. [Filing issues against Microsoft's Defender crap could actually fix these recurring false positive alarms.]

**Comment by SingingBush** [comment]
I believe the better option would actually be for @Manuzor to move the https://github.com/Manuzor/chocolatey-packages repo to be under the ldc-developers group and have signed packages being made available to chocolatey every time a ldc release is published. I cannot raise an issue on his project though as they're disabled.

I tried reporting the false positive to microsoft but it seems that it can only be done on a per file basis so I cannot do anything the will help with future releases. Signed binaries and distribution of releases should totally be ldc-developers problem, regardless of whether you currently maintain that method of distribution.

**Comment by Manuzor** [comment]
@SingingBush Thank you for @-ing me, I would never have come across this otherwise as I'm not actively using ldc right now. I've opened the issues for https://github.com/Manuzor/chocolatey-packages again, not sure why they were disabled in the first place.

The chocolatey package only re-distributes whatever is uploaded to github. This is a completely automated process that basically just does search and replace on old URLs with new URLs for every release. I don't re-pack or build anything from scratch.

I've had issues in my automation scripts since 1.24 that I have fixed in the last couple of days, that's why there haven't been any updates. 1.26 is currently pending on the chocolatey community package repository, but it has been flagged as containing a virus, as you may see here: https://community.chocolatey.org/packages/ldc/1.26.0

I guess this is the same issue that we're talking about here. I'm not sure, however, how it would help to move the repository to https://github.com/ldc-developers/chocolatey-packages. I'm also not sure what you mean by "signed packages". Anyone manually downloading from the github releases page will still run into these false positives from Defender.

That being said, I'm open to moving (or transferring ownership of) my ldc chocolatey package, if that helps in some way.

**Comment by SingingBush** [comment]
Thanks Manuzor. I thought your packages would build from source. There was mention in the linked (https://github.com/ldc-developers/ldc/issues/3472) ticket that dmd had the same problems prior to code signing their release builds.

My thoughts on the ownership aspect is that when there is a group/organisation responsible for it, there is less likelihood for a situation in which those releases stop going out. Having a single person being responsible keeping the ldc package on chocolatey up to date causes an increased risk that maintenance can stop at any time.

**Comment by Manuzor** [comment]
> My thoughts on the ownership aspect is that when there is a group/organisation responsible for it, there is less likelihood for a situation in which those releases stop going out. Having a single person being responsible keeping the ldc package on chocolatey up to date causes an increased risk that maintenance can stop at any time.

That is indeed a risk since I haven't touched ldc or D in a couple of years, and I haven't used [chocolatey][chocolatey] in favor of [scoop][scoop] for quite some time as well, and I don't see myself going back (for various reasons). The only reason I keep maintaining it is because I'm leaning on automation scripts, AppVeyor, and ldc releases on GitHub. The current process is pretty easy to keep up and running and not very time consuming.

But evidently, from time to time, some things pop up where I have to manually intervene. I haven't set up email Notifications for AppVeyor build failures yet, so I only notice issues "by chance", basically. I'm not sure I'd be willing to keep up with maintaining the package should such issues pile up more frequently, because, quite frankly, I don't get anything out of it other than the satisfaction of knowing to be of service to a probably very small part of the ldc/D community (which I'm not actively participating in, either...)

That being said, I don't plan to drop support for the ldc chocolatey package anytime soon, as long as it keeps sailing as smoothly as it did so far.

If the ldc maintainers are willing to take over, I'd be happy to transfer my repo and help with the transition as best I can. ldc is the only package in my chocolatey repository, so there's not even anything to split out or anything. Stuff in the [.appveyor.yml](https://github.com/Manuzor/chocolatey-packages/blob/master/.appveyor.yml) would obviously need to be adjusted (e.g. GitHub access tokens), but other than that, the transfer shouldn't be much of a hassle.

At this point, I would like to humbly encourage the ldc maintainers to consider supporting ldc (and maybe related packages) on Windows package managers such as [chocolatey][chocolatey] and [scoop][scoop]. In my opinion, these things substantially improve the user experience of bootstrapping a new machine, making sure everyone on the team is on the same version, and keeping up to date with the latest versions. To give some perspective, according to the chocolatey page, the [ldc package](https://community.chocolatey.org/packages/ldc) has been downloaded over 13000 times (across all versions) since I uploaded it there in 2017. So it seems people do make use of it. And in contrast, I maybe had to spend 2-3 hours per year maintaining it so far. It sounds like a good time investment to me. I assume other people that know more about automation of this kind (e.g. by using GitHub Actions) will have an even easier time than me keeping it running smoothly.

[chocolatey]: https://community.chocolatey.org/
[scoop]: https://scoop.sh

**Comment by kinke** [comment]
First of all, thanks for providing that package and keeping on maintaining it, all the more as you don't use it yourself any longer. Speaking for myself, I can't take any more on my plate, and have drawn that line a while ago - relying on good guys like you willing to spend some time for others by providing an easy install via their favourite package manager or other deployment method. It's not just Windows, this goes for the Linux distro packages as well.

Moving a repo to the ldc-developers GitHub org doesn't really change anything, it all boils down to people's interests and time budget/focus in the end. If automation is simplified by having a CI job run here in this repo directly (e.g., for each tagged build), pull requests are warmly welcome!
