### ISSUE TITLE
 Error: function ldc.intrinsics.llvm_bswap!uint.llvm_bswap conflict with std.bitmanip.nativeToBigEndian!ushort.nativeToBigEndian ?

### ISSUE THREAD

**Issue by mingwugmail** [ldc-developers/ldc#3772]
Hi,

While building apache-thrift, LDC has build failure (DMD succeed):

/home/./.dub/packages/apache-thrift-0.14.1/apache-thrift/lib/d/src/thrift/transport/websocket.d(335,39): Error: function ldc.intrinsics.llvm_bswap!uint.llvm_bswap at /home/./project/ldc2-1.26.0-linux-x86_64/bin/../import/ldc/intrinsics.di(405,7) conflicts with function std.bitmanip.nativeToBigEndian!ushort.nativeToBigEndian at /home/./project/ldc2-1.26.0-linux-x86_64/bin/../import/std/bitmanip.d(2998,6)

While there is a work around by using fully qualified names: `std.bitmanip.nativeToBigEndian`, I think LDC compiler should be fixed.

```
$ ldc2 --version
LDC - the LLVM D compiler (1.26.0):
  based on DMD v2.096.1 and LLVM 11.0.1
  built with LDC - the LLVM D compiler (1.26.0)
  Default target: x86_64-unknown-linux-gnu
  Host CPU: znver1
  http://dlang.org - http://wiki.dlang.org/LDC
```

**Comment by kinke** [comment]
This looks like a frontend bug - the conflict seems to be caused by https://github.com/ldc-developers/phobos/blob/16d1a9be59cb319961bd7bc0bcd1128151fc0a67/std/digest/sha.d#L124, which is a **private** alias, which - for LDC - aliases 2 other aliases: https://github.com/ldc-developers/druntime/blob/8916695501005be33291f5a88e399b7eb1eb9e25/src/core/bitop.d#L657 and https://github.com/ldc-developers/druntime/blob/8916695501005be33291f5a88e399b7eb1eb9e25/src/core/bitop.d#L677

**Comment by mingwugmail** [comment]
Thanks for the confirmation. Hope this will be fixed on the LDC side.

**Comment by kinke** [comment]
This needs further investigation (reduced test case), and then filed as DMD issue.

**Comment by kinke** [comment]
Filed upstream as https://issues.dlang.org/show_bug.cgi?id=22083, thanks.
