### ISSUE TITLE
Incorrect compilation when adding a 64-bit constant to a link-time address

### ISSUE THREAD

**Issue by zyedidia** [ldc-developers/ldc#4264]
This code adds a large constant to the address of main, but the addition doesn't actually seem to be performed.

```d
import core.stdc.stdio;
enum offset = 0xFFFF_FFFF_0000_0000UL;
extern (C) void main() {
    // auto offset = offset;
    printf("0x%llx\n", cast(ulong)&main);
    printf("0x%llx\n", cast(ulong)&main + offset);
    assert((cast(ulong)&main) != (cast(ulong)&main + offset));
}
```

`&main + offset` should not be equal to `main`, but it is with LDC 1.30.0 and DMD 2.098.0 (causing an assertion failure). The test passes with GDC 10.3.0 though. The problem only seems to occur when `offset` is a constant greater than 32 bits.

If I uncomment the line `auto offset = offset`, then it passes on all compilers.

Thanks for your help.

**Comment by JohanEngelen** [comment]
This is indeed a bug in LDC. We assume `unsigned` (32bit) for `DtoGEP` indices.
Strangely, this code works in 32-bit mode (`-m32`) because in that case the frontend AST does an addition in `ulong` domain. In 64-bit mode, the frontend removes the `ulong` cast, and the addition is done as pointer math... weird.

**Comment by zyedidia** [comment]
Should this also be reported to DMD since it seems like a frontend issue?
