### ISSUE TITLE
Windows installer installs to Administrator path when installed from limited user

### ISSUE THREAD

**Issue by schveiguy** [ldc-developers/ldc#4494]
The Windows installer requires an administrator to install. If the user doing the install is a limited user, this means an administrator types in their password, and it runs under that user.

Once at the end, LDC asks if you want to add LDC to the current user's path. However, what it does is add it to the *Administrator* user's path.

This results in the path not being altered for the user who requested the install.

I propose that the default should be to alter the system path, which is shared by all users. At least the checkbox option should be there to install system-wide path.

**Comment by kinke** [comment]
It's been a while, but fortunately there's still a comment wrt. how to install it properly as non-admin: https://github.com/ldc-developers/ldc/blob/d70f676e50339d6edcbda96d0c2e8d689d6844ab/packaging/windows_installer.iss#L17-L18

Using `HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\Path` for admin installs might make sense.

**Comment by schveiguy** [comment]
I'll put it this way. Currently, when you install as a non-admin user:

1. It asks for an admin password
2. At the end it says "Add to PATH environment variable for current user"

2 is misleading, and doesn't help the "current user". From a user perspective this just doesn't do what it's saying it's doing (even though it is doing *something*).

So even if doing the path thing for the system doesn't make sense, the current situation is wrong.

> Using `HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Environment\Path` for admin installs might make sense.

I'm not sure what this one does, where are these keys documented?

**Comment by kinke** [comment]
I'm pretty sure this worked fine for my local tests back then, with an admin-able user (so just approving of elevated privileges). So I take it this problem is for a user which does not install it locally via that InnoSetup-standard `/CURRENTUSER` switch, then apparently requiring to impersonate an admin user, which is then the current_user for the installation and so gets the registry PATH entry.

> I'm not sure what this one does, where are these keys documented?

AFAICT, those are the 'system' env vars you mentioned: https://learn.microsoft.com/en-us/windows/win32/procthread/environment-variables

So I guess having a 2nd check box in admin install mode, to add it to system PATH, would make sense - I wouldn't want to lose the ability to just add it to my (admin-able) user.

**Comment by schveiguy** [comment]
> So I guess having a 2nd check box in admin install mode, to add it to system PATH, would make sense - I wouldn't want to lose the ability to just add it to my (admin-able) user.

Yeah, that would be perfect!
