### ISSUE TITLE
importC `__asm` error: implicit string concatenation is error-prone and disallowed in D

### ISSUE THREAD

**Issue by kassane** [ldc-developers/ldc#4785]
**OS:** Arch-Linux
**Arch:** x86_64 (zen3)
**LDC version:** master (v1.40.x based)

I selected an isolated test from the pico-sdk api. Based on my hobby project: https://github.com/kassane/rp2040-dlang

<details>
<summary>importedC code</summary>

code: https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2040/pico_platform/include/pico/platform.h#L104

```c
#include <stdint.h>

#ifdef __ARM_ARCH_ISA_THUMB
#define pico_default_asm(...) __asm(".syntax unified\n" __VA_ARGS__)
#define pico_default_asm_volatile(...)                                         \
  __asm volatile(".syntax unified\n" __VA_ARGS__)
#define pico_default_asm_goto(...) __asm goto(".syntax unified\n" __VA_ARGS__)
#else
#define pico_default_asm(...) __asm(__VA_ARGS__)
#define pico_default_asm_volatile(...) __asm volatile(__VA_ARGS__)
#define pico_default_asm_goto(...) __asm goto(__VA_ARGS__)
#endif

static inline void busy_wait_at_least_cycles(uint32_t minimum_cycles) {
  pico_default_asm_volatile("1: subs %0, #3\n"
                            "bcs 1b\n"
                            : "+l"(minimum_cycles)
                            :
                            : "cc", "memory");
}
```
</details>
<details>
<summary>output</summary>

```console
$ ldc2 -o- -H test.c -mtriple=arm-unknown-unknown-eabi -mcpu=cortex-m0plus --verrors-context
test.c(15): Error: implicit string concatenation is error-prone and disallowed in D
  pico_default_asm_volatile("1: subs %0, #3\n"
                             ^
test.c(15):        Use the explicit syntax instead (concatenating literals is `@nogc`): "1: subs %0, #3\n" ~ "bcs 1b\n"
```
</details>

**Comment by kinke** [comment]
I've hit this too, along with missing GNU builtins etc. - but all of these problems, coming from inline functions in the C headers using GNU-specific inline assembly and/or builtins, vanish when not *compiling* the .c file with the D compiler, but just *importing* it from D, to get the bindings only. Then the C function bodies aren't semantically analyzed and codegen'd, and as long as you don't actually call any of these `static inline` functions directly from D, you should be fine (otherwise you're gonna see undefined symbols when linking).

Your `-o- -H` still does a full semantic analysis of the C file.

**Comment by kassane** [comment]
Got It!
