### ISSUE TITLE
Win64 failing unittests

### ISSUE THREAD

**Issue by Trass3r** [ldc-developers/ldc#758]
Let's collect information about the failing unittests.
* `_d_arraycatnT` contains varargs and crashes. Responsible for rt.lifetime, core.time, std.array, std.conv,... probably most of them.
  Potentially related to #702 #73 #699
* std.complex test fails @ line 480 with c1^^c2 cause of some weirdness in std.math atan2(real y, real x) leading to arg(1+i) to be 0. #761 
* core.thread is weird crash in ntdll.dll!RtlDispatchException()

**Comment by kinke** [comment]
Update:
39 failures with LLVM 3.7 (d89ac8f158976eaa9f9bcfba88f8a679771704f8), LDC head (with /LARGEADDRESSAWARE:NO adaptations) and VS 2013/Win8 x64:
```
core.thread
std.algorithm
std.complex
std.conv
std.csv
std.datetime
std.math
std.numeric
std.parallelism
std.path
std.process
std.regex
std.stream
std.uni
std.uri
std.zlib
std.net.isemail
std.internal.math.errorfunction
std.internal.math.gammafunction
std.algorithm-debug
std.complex-debug
std.conv-debug
std.csv-debug
std.datetime-debug
std.json-debug
std.math-debug
std.numeric-debug
std.parallelism-debug
std.path-debug
std.process-debug
std.regex-debug
std.socket-debug
std.stream-debug
std.uni-debug
std.uri-debug
std.zlib-debug
std.net.isemail-debug
std.internal.math.errorfunction-debug
std.internal.math.gammafunction-debug
```

**Comment by kinke** [comment]
I'll go ahead with VS 2015 CTP 6 ;) - not too bad, 58 failures:
```
         19 - core.thread (SEGFAULT)
        147 - std.algorithm (Failed)
        148 - std.array (Failed)
        151 - std.bigint (Failed)
        156 - std.conv (Failed)
        157 - std.cstream (Failed)
        158 - std.csv (Failed)
        159 - std.datetime (Failed)
        161 - std.encoding (Failed)
        164 - std.format (Failed)
        168 - std.math (Failed)
        174 - std.parallelism (SEGFAULT)
        175 - std.path (Failed)
        176 - std.process (Failed)
        179 - std.regex (Failed)
        181 - std.socket (Failed)
        184 - std.stdio (Failed)
        186 - std.stream (SEGFAULT)
        187 - std.string (Failed)
        190 - std.traits (Failed)
        194 - std.uni (Failed)
        195 - std.uri (Failed)
        201 - std.zlib (Failed)
        209 - std.digest.crc (Failed)
        211 - std.digest.md (Failed)
        212 - std.digest.ripemd (Failed)
        213 - std.digest.sha (Failed)
        215 - std.net.isemail (SEGFAULT)
        221 - std.internal.math.gammafunction (Failed)
        390 - std.algorithm-debug (Failed)
        391 - std.array-debug (Failed)
        394 - std.bigint-debug (Failed)
        399 - std.conv-debug (Failed)
        400 - std.cstream-debug (Failed)
        401 - std.csv-debug (Failed)
        402 - std.datetime-debug (Failed)
        404 - std.encoding-debug (Failed)
        407 - std.format-debug (Failed)
        410 - std.json-debug (Failed)
        411 - std.math-debug (Failed)
        417 - std.parallelism-debug (SEGFAULT)
        418 - std.path-debug (Failed)
        419 - std.process-debug (Failed)
        422 - std.regex-debug (Failed)
        424 - std.socket-debug (Failed)
        427 - std.stdio-debug (Failed)
        429 - std.stream-debug (SEGFAULT)
        430 - std.string-debug (Failed)
        433 - std.traits-debug (Failed)
        437 - std.uni-debug (Failed)
        438 - std.uri-debug (Failed)
        444 - std.zlib-debug (Failed)
        452 - std.digest.crc-debug (Failed)
        454 - std.digest.md-debug (Failed)
        455 - std.digest.ripemd-debug (Failed)
        456 - std.digest.sha-debug (Failed)
        458 - std.net.isemail-debug (SEGFAULT)
        464 - std.internal.math.gammafunction-debug (Failed)
```
with https://github.com/ldc-developers/phobos/pull/6 and https://github.com/ldc-developers/druntime/pull/17 (don't forget to uncomment ```version = LDC_MSVCRT14;``` in the druntime files).

A new common issue seems to have arised (assertion in CRT) which probably accounts for most differences compared to MSVCRT 12.
MSVCRT 14 fixes highly problematic https://github.com/ldc-developers/ldc/issues/761. We can't fix that easily otherwise.

**Comment by kinke** [comment]
Now down to 39 failures with MSVCRT 14 by simply disabling a printf() call in test_runner.d after a _successful_ unit-test run, the printf() call _inside_ the try-block. There's apparently some serious corruption going on as otherwise I get a MSVCRT assertion failure
```
Expression: (fh >= 0 && (unsigned)fh < (unsigned)_nhandle)
```
in isatty() called by printf() which probably checks that stdout points to a valid handle.
By disabling the try-catch-block altogether and instead simply invoking fp(), a bunch of randomly selected failing Phobos-debug tests according to VS debugger all fail in ldc.eh2._d_eh_personality:364 due to an access violation:
```
if (_d_isbaseof(excobj.classinfo, catch_ci))
```
with excobj being null. The call stack is full of _d_eh_personality() frames.
I guess exception handling is still the #1 blocker for Win64.

**Comment by kinke** [comment]
Only remaining failing unittest nowadays is core.thread, which fails in release in line https://github.com/ldc-developers/druntime/blob/ldc/src/core/thread.d#L5467, a Win64-specific test.

**Comment by kinke** [comment]
The status is still the same. https://github.com/ldc-developers/ldc/issues/1103 points to the single remaining 'issue' incl. details, so I'm going to close this.
