### ISSUE TITLE
Doesn't compile with LLVM 3.7 (Trunk).

### ISSUE THREAD

**Issue by christinaa** [ldc-developers/ldc#833]
Doesn't seem to work with the latest LLVM trunk because a couple of things changed, including the initialize method of `cl::parser` and `TargetLibraryInfo` being replaced by `TargetLibraryInfoImpl`.

I tried to fix what I could but I don't know how to fix LLVM not detecting the extra arguments now (getExtraOptionNames appears to be ignored)

Here's my "fix": https://github.com/christinaa/ldc/commit/7de10aec75e3306e87ed17fd30129b779844b2d1

**Comment by redstar** [comment]
Thanks for providing the code. I already commited the `TargetLibraryInfo` part of it.
Regarding the commandline options I also need to investigate the new LLVM approach.

If you provide small pull requests then I am happy to merge them. :-)

**Comment by redstar** [comment]
The change to the command line options is annoying. The option is stored in a hash map before the `FlagParser` is initialized. Changes to the `ArgStr` are ignored because only the hash map is used to identify the option.
My current solution is to remove `FlagParser` and create 2 options: an `enable-` option and a `disable-` option. The latter one needs to be really hidden and uses the storage of the other option. Better ideas welcome.

**Comment by redstar** [comment]
Fixed with commit 56a0aa00ebb2505772a8b80c342f88776d79e737.
Some source reading revealed that the `FlagParser` can be fixed in a way similar to the original implementation.
