### ISSUE TITLE
MSVC: inconsistent parsing of floating point strings

### ISSUE THREAD

**Issue by kinke** [ldc-developers/ldc#931]
```D
import core.stdc.stdlib, std.conv, std.stdio;

void check(T)()
{
    string str = "3673.562";

    T ct = 3673.562;

    static if (is(T == real))
        alias strtod = strtold;
    else if (is(T == float))
        alias strtod = strtof;

    char* dummy;
    T rt_strtod = strtod(str.ptr, &dummy);

    T rt_to = to!T(str);

    writefln("ct = %a, strtod = %a, to = %a", ct, rt_strtod, rt_to);
}

void main()
{
    check!real();
    check!double();
    check!float();
}
```

Linux x64:
```
ct = 0xe.598fdf3b645a1cbp+8, strtod = 0xe.598fdf3b645a1cbp+8, to = 0xe.598fdf3b645a1cbp+8
ct = 0x1.cb31fbe76c8b4p+11, strtod = 0x1.cb31fbe76c8b4p+11, to = 0x1.cb31fbe76c8b4p+11
ct = 0x1.cb31fcp+11, strtod = 0x1.cb31fcp+11, to = 0x1.cb31fcp+11
```

Win64, w/ merge-2.067 and VS2015:
```
ct = 0x1.cb31fbe76c8b4p+11, strtod = 0x1.cb31fbe76c8b4p+11, to = 0x1.cb31fbe76c8b5p+11
ct = 0x1.cb31fbe76c8b4p+11, strtod = 0x1.cb31fbe76c8b4p+11, to = 0x1.cb31fbe76c8b5p+11
ct = 0x1.cb31fc0000000p+11, strtod = 0x1.cb31fc0000000p+11, to = 0x1.cb31fc0000000p+11
```

So `std.conv.to!double(string)` doesn't work as expected on Win64 and in this case apparently rounds up the result. This leads to a failing unittest in `std.csv`.
It could be an upstream issue; at least in my opinion, `to!double(string)` should return exactly the same value on all platforms. The responsible function is https://github.com/ldc-developers/phobos/blob/ldc-merge-2.067/std/conv.d#L2377, and it seems to parse a native `real` value and then casting it to the desired return type, so that the result may depend on the native `real` type (80-bit on Linux x64 vs. 64-bit on MSVC).

**Comment by smolt** [comment]
I recognize the number 3673.562 well.  Cross compiling to iOS has same issue because real is only 64-bits.  I had been meaning to write something up on this but it started getting time consuming for a single bit.  Initially I wanted to say `to!double()` and compiler literals (produced by host `strtold`) should always produce same number, but then started to wonder if I was being too picky after reading:

http://www.exploringbinary.com/how-strtod-works-and-sometimes-doesnt/

More discussion:

http://forum.dlang.org/thread/jnkiposzgjkzzucrrvvb@forum.dlang.org#post-m2385o1166.fsf:40comcast.net

Cross-compiling has related problem where ctfe `to!double` and runtime `to!double` may not match if host and target have different reals, but Kai has been working on that.

I did start an experiment to have std.conv.to and parse functions use libc `strtod` family instead of its D code, but got hung up on something.

**Comment by kinke** [comment]
Thx Dan for explanation + links. So I guess the best workaround/fix would be using hex fp literals for this kind of tests.

**Comment by kinke** [comment]
This `std.csv` test has already been fixed upstream: https://github.com/D-Programming-Language/phobos/commit/608ff995afe40fcf7aa147af2c4b758a14a5784c
